[package]
name = "nautilus_experiments"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
datafusion = "42.0.0"
datafusion-expr = "42.0.0"
futures = "0.3.30"
tokio = { version = "1.37.0", features = ["rt-multi-thread"] }
